### ISSUE TITLE
"Correct hash" determined incorrectly

### ISSUE THREAD

**Issue by atenfyr** [Trystan-Cannon/Java-Krist-Miner#4]
When detecting if a hash is correct (i.e gives you KST), you need to detect if it is lower than the latest target, not the latest block. In your miner, it is compared to the lastest block. The current target can be found at http://65.26.252.225/quest/dia/krist/?getwork (?getwork). (Is also fixed by #3 pull request)

**Comment by oldmud0** [comment]
Yeah, I'm making a huge pull req right now. If you don't mind a few bugs, you can use my fork and build it from source.

**Comment by cpixelcube** [comment]
I'm already using yours, oldmud. :)

**Comment by oldmud0** [comment]
?
